version: '3'
services:
  fpm:
    build: ./fpm
    tty: true
    working_dir: /var/www/notificator
    volumes:
      - ../.:/var/www/notificator:cached
      - ./fpm/config/php.ini-local:/usr/local/etc/php/php.ini:ro

  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www/notificator
    ports:
      - "80:80"
    volumes:
      - ../.:/var/www/notificator:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: "notificator"
      POSTGRES_USER: "notificator"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"

  redis:
      image: redis:alpine
      command: redis-server --appendonly yes
      volumes:
          - ./data/redis:/data
      ports:
          - "8002:6379"
