name: Tests
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: pdo pdo_pgsql bcmath sockets
      - run: echo "Composer dependencies have been installed"
      - run: cp .env.example .env
      - run: vendor/bin/phpunit
